//
//  ProviderToken.swift
//  SmartSpend
//
//  Created by shortcut mac on 17.8.25.
//

import Foundation

/// Token/info returned from the Apple SDK (and forwarded to backend)
public struct ProviderToken: Codable {
    public let provider: String            // "apple"
    public let idToken: String?            // Apple's identity token (JWT) — may be nil if auth-code-only
    public let authorizationCode: String?  // server code (if present)
    public let rawNonce: String?           // raw nonce generated by app
    public let userID: String?             // Apple user identifier (credential.user)
    public let email: String?              // email (only provided on first sign-in)
    public let givenName: String?          // givenName (only on first sign-in)
    public let familyName: String?         // familyName (only on first sign-in)
}
