import Foundation

/// Token/info returned from the Apple SDK (and forwarded to backend)
public struct ProviderToken: Codable {
    public let provider: String            // "apple" or "google"
    public let idToken: String?            // Apple's identity token (JWT) - REQUIRED for your flow
    public let authorizationCode: String?  // server code (optional)
    public let rawNonce: String?           // raw nonce generated by app
    public let userID: String?             // Apple user identifier
    public let email: String?              // email (only provided on first sign-in)
    public let givenName: String?          // givenName (only on first sign-in)
    public let familyName: String?         // familyName (only on first sign-in)
    
    public init(provider: String, idToken: String?, authorizationCode: String? = nil, rawNonce: String? = nil, userID: String? = nil, email: String? = nil, givenName: String? = nil, familyName: String? = nil) {
        self.provider = provider
        self.idToken = idToken
        self.authorizationCode = authorizationCode
        self.rawNonce = rawNonce
        self.userID = userID
        self.email = email
        self.givenName = givenName
        self.familyName = familyName
    }
}
